name: Detect and Tag New Version
description: >
  Tag new versions in your repository based on changes to its contents, like a
  `package.json` or `.gemspec` file.
author: dfreeman
inputs:
  version-command:
    description: >
      A shell command whose output when executed will be considered the version
      of your repository for the commit at which it's currently checked out.
  create-tag:
    description: >
      Whether or not a tag should be created if a new version is detected.
    default: true
  tag-template:
    description: >
      A template for producing a tag name from the current version of your
      repository, replacing '{VERSION}' with the deteced version.
    default: 'v{VERSION}'
  tag-annotation-template:
    description: >
      A template for producing a tag annotation from the current version of your
      repository, replacing '{VERSION}' with the deteced version. May be set to
      an empty string to produce a lightweight (i.e. annotation-less) tag.
    default: 'Released version {VERSION}'
outputs:
  previous-version:
    description: the detected previous version of this repository
  current-version:
    description: the detected current version of this repository
  tag:
    description: if a new tag is created, this output will contain its name
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: tag
  color: purple
